title: OS2valghalla
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
just_the_docs:
  toc_title: "INDHOLD"


url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

defaults:
  - scope:
      path: ""         # alle filer i hele repoet
      type: "pages"    # markdown-sider
    values:
      layout: "default"
      has_toc: false # kommentar: fjerne 'Table of contents'

#color_scheme: custom

# Tilføj denne del for at ændre teksten via CSS
head_html: |
  <style>
    .toc-title {
      display: none !important;
    }
    .toc-title::after {
      content: "INDHOLD";
      display: block;
      font-weight: bold;
    }
  </style>
